### PR TITLE
Teleport sound and player placeholder

### PR DESCRIPTION
**Pull request by velnias75**
* Play an enderman sound when player teleports to their home (configuable)
* Added a placeholder for a team formatted player name (not yet used everywhere)

### CODE REVIEW

**Comment by hyperdefined** [comment]
I like the teleport effect, but what is the scoreboard for?

**Comment by velnias75** [comment]
The scoreboard is to get the plyers team.
You can format a players name with the `/team`-command and give a color, a prefix and/or a suffix. Minecraft will use this formatting almost everywhere, esp. in chat messages.

I could add a config to my patch fpr enabling/disabling this feature.

**Comment by hyperdefined** [comment]
Ah, I never thought of using the player's "formatted" name instead of their username. I think a configuration option would be best just so people have more freedom.

**Comment by velnias75** [comment]
> Ah, I never thought of using the player's "formatted" name instead of their username. I think a configuration option would be best just so people have more freedom.

Ok, I will add a configuration option to the patch.

**Comment by hyperdefined** [comment]
Looks good, I will merge it and fix somethings up.

**Comment by velnias75** [comment]
> Looks good, I will merge it and fix somethings up.

**Thanks** 😺

*BTW: I've added your project to [Open Hub](https://www.openhub.net/p/EzHomes/), for adding my commits into my profile.*

**Pull request merged**
